# Generated by Django 4.2.7 on 2025-09-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='default_ai_model',
            field=models.CharField(default='gemini-1.5-flash', max_length=50, verbose_name='Default AI Model'),
        ),
    ]
