# Generated by Django 4.2.24 on 2025-09-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_gemini_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='default_ai_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=50, verbose_name='Default AI Model'),
        ),
    ]
