# Generated by Django 4.2.24 on 2025-09-28 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Exam'), ('syllabus', 'Syllabus'), ('lesson', 'Lesson'), ('assignment', 'Assignment'), ('other', 'Other')], max_length=50, verbose_name='Content Type')),
                ('content_title', models.CharField(max_length=200, verbose_name='Content Title')),
                ('content_id', models.PositiveIntegerField(help_text='ID of the related content object', verbose_name='Content ID')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='Share Count')),
                ('edit_count', models.PositiveIntegerField(default=0, verbose_name='Edit Count')),
                ('total_time_spent', models.PositiveIntegerField(default=0, verbose_name='Total Time Spent (seconds)')),
                ('average_session_time', models.FloatField(default=0.0, verbose_name='Average Session Time (seconds)')),
                ('bounce_rate', models.FloatField(default=0.0, help_text='Percentage of users who left without interaction', verbose_name='Bounce Rate (%)')),
                ('load_time_avg', models.FloatField(default=0.0, verbose_name='Average Load Time (seconds)')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Error Count')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('difficulty_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Difficulty Level')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('first_accessed', models.DateTimeField(auto_now_add=True, verbose_name='First Accessed')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Last Accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_analytics', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Analytics',
                'verbose_name_plural': 'Content Analytics',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['user', 'content_type', '-last_accessed'], name='analytics_c_user_id_f737d9_idx'), models.Index(fields=['course', '-last_accessed'], name='analytics_c_course__a3ae3b_idx'), models.Index(fields=['content_type', '-view_count'], name='analytics_c_content_e384ee_idx')],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
    ]
