name: didactia
services:
- build_command: pip install -r requirements-fixed.txt
  environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/didactia
  health_check:
    http_path: /
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
  run_command: gunicorn didactia_project.wsgi:application --bind 0.0.0.0:8000
  source_dir: /
  envs:
  - key: DJANGO_SETTINGS_MODULE
    value: didactia_project.production_settings
  - key: DEBUG
    value: "False"
  - key: PYTHON_VERSION
    value: "3.11"

databases:
- engine: PG
  name: didactia-db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"