# Generated by Django 4.2.24 on 2025-09-28 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications', verbose_name='Email Notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_public',
            field=models.BooleanField(default=False, help_text='Make profile visible to other users', verbose_name='Public Profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Display email address on public profile', verbose_name='Show Email'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('account_created', 'Account Created'), ('login', 'Login'), ('logout', 'Logout'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('course_created', 'Course Created'), ('course_updated', 'Course Updated'), ('file_uploaded', 'File Uploaded'), ('content_generated', 'Content Generated'), ('export_created', 'Export Created'), ('settings_updated', 'Settings Updated')], max_length=30, verbose_name='Activity Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Activity Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
