# Generated by Django 4.2.24 on 2025-09-23 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('course_code', models.CharField(blank=True, help_text='e.g., CS101, MATH200', max_length=20, null=True, verbose_name='Course Code')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('semester', models.CharField(blank=True, choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer'), ('winter', 'Winter')], max_length=10, null=True, verbose_name='Semester')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German')], default='en', max_length=10, verbose_name='Course Language')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=20, verbose_name='Status')),
                ('credits', models.IntegerField(blank=True, null=True, verbose_name='Credits')),
                ('max_students', models.IntegerField(blank=True, null=True, verbose_name='Maximum Students')),
                ('syllabus', models.TextField(blank=True, null=True, verbose_name='Syllabus')),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='List of learning objectives for the course', verbose_name='Learning Objectives')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags to categorize the course', verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-updated_at'],
                'unique_together': {('instructor', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CourseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_generate_quizzes', models.BooleanField(default=False, verbose_name='Auto Generate Quizzes')),
                ('quiz_generation_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='manual', max_length=20, verbose_name='Quiz Generation Frequency')),
                ('default_quiz_questions', models.IntegerField(default=10, verbose_name='Default Quiz Questions')),
                ('exam_versions_count', models.IntegerField(default=3, verbose_name='Exam Versions Count')),
                ('allow_file_sharing', models.BooleanField(default=True, verbose_name='Allow File Sharing')),
                ('notification_settings', models.JSONField(blank=True, default=dict, verbose_name='Notification Settings')),
                ('branding_settings', models.JSONField(blank=True, default=dict, help_text='Custom branding for exports (logo, colors, etc.)', verbose_name='Branding Settings')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Settings',
                'verbose_name_plural': 'Course Settings',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Module Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Module Content')),
                ('learning_outcomes', models.JSONField(blank=True, default=list, verbose_name='Learning Outcomes')),
                ('duration_hours', models.FloatField(blank=True, null=True, verbose_name='Duration (hours)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
