# Generated by Django 4.2.24 on 2025-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('hi', 'Hindi'), ('tr', 'Turkish'), ('el', 'Greek')], default='en', max_length=10, verbose_name='Course Language'),
        ),
    ]
