# Generated by Django 4.2.24 on 2025-09-23 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exports.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('ai_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Export Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('html', 'HTML'), ('zip', 'ZIP Archive'), ('json', 'JSON')], max_length=20, verbose_name='Export Format')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Export configuration and options', verbose_name='Export Parameters')),
                ('branding_settings', models.JSONField(blank=True, default=dict, help_text='Custom branding (logo, colors, university info)', verbose_name='Branding Settings')),
                ('include_answer_key', models.BooleanField(default=True, verbose_name='Include Answer Key')),
                ('include_instructions', models.BooleanField(default=True, verbose_name='Include Instructions')),
                ('watermark', models.CharField(blank=True, max_length=200, null=True, verbose_name='Watermark')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to=exports.models.export_file_path, verbose_name='Generated File')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('processing_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Processing Time (seconds)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this export file should be automatically deleted', null=True, verbose_name='Expires At')),
                ('last_downloaded', models.DateTimeField(blank=True, null=True, verbose_name='Last Downloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='courses.course')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='ai_generator.aigeneration')),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('pdf', 'PDF Template'), ('docx', 'Word Template'), ('html', 'HTML Template'), ('latex', 'LaTeX Template')], max_length=20, verbose_name='Template Type')),
                ('content_type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Exam'), ('syllabus', 'Syllabus'), ('flashcards', 'Flashcards'), ('report', 'Report'), ('certificate', 'Certificate')], max_length=20, verbose_name='Content Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='export_templates/', verbose_name='Template File')),
                ('template_content', models.TextField(blank=True, help_text='Template content for HTML/text-based templates', null=True, verbose_name='Template Content')),
                ('css_styles', models.TextField(blank=True, null=True, verbose_name='CSS Styles')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Available variables and their descriptions', verbose_name='Template Variables')),
                ('is_system_template', models.BooleanField(default=False, verbose_name='System Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Usage Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Template',
                'verbose_name_plural': 'Export Templates',
                'ordering': ['-usage_count', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shared_with_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Shared with Email')),
                ('can_download', models.BooleanField(default=True, verbose_name='Can Download')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Access Count')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='exports.exportjob')),
            ],
            options={
                'verbose_name': 'Export Share',
                'verbose_name_plural': 'Export Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], max_length=10, verbose_name='Log Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exports.exportjob')),
            ],
            options={
                'verbose_name': 'Export Log',
                'verbose_name_plural': 'Export Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exportjob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to='exports.exporttemplate'),
        ),
        migrations.CreateModel(
            name='ExportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_letter', models.CharField(default='A', max_length=1, verbose_name='Version Letter')),
                ('generated_file', models.FileField(upload_to=exports.models.export_file_path, verbose_name='Generated File')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('variations', models.JSONField(blank=True, default=dict, help_text='Specific variations applied to this version', verbose_name='Version Variations')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='exports.exportjob')),
            ],
            options={
                'verbose_name': 'Export Version',
                'verbose_name_plural': 'Export Versions',
                'ordering': ['version_letter'],
                'unique_together': {('export_job', 'version_letter')},
            },
        ),
    ]
