# Generated by Django 4.2.7 on 2025-09-24 10:15

from django.db import migrations, models
import exports.models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportversion',
            name='generated_file',
            field=models.FileField(upload_to=exports.models.export_version_file_path, verbose_name='Generated File'),
        ),
    ]
