# Generated by Django 4.2.24 on 2025-09-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_alter_exportversion_generated_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='university_logo',
            field=models.ImageField(blank=True, help_text='Upload university logo for branding in exports', null=True, upload_to='export_logos/', verbose_name='University Logo'),
        ),
    ]
