# Generated by Django 4.2.24 on 2025-10-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_exportjob_university_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='export_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('html', 'HTML')], max_length=20, verbose_name='Export Format'),
        ),
    ]
