# Generated by Django 4.2.24 on 2025-09-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        ('ai_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneration',
            name='source_files',
            field=models.ManyToManyField(blank=True, help_text='Source files used for generation', related_name='ai_generations', to='uploads.uploadedfile'),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='ai_generator.generationtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='generationversion',
            unique_together={('original_generation', 'version_letter')},
        ),
        migrations.AlterUniqueTogether(
            name='generationfeedback',
            unique_together={('generation', 'user', 'feedback_type')},
        ),
    ]
