# Generated by Django 4.2.7 on 2025-09-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generator', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneration',
            name='ai_model',
            field=models.CharField(default='gemini-1.5-flash', max_length=50, verbose_name='AI Model'),
        ),
    ]
