# Generated by Django 4.2.24 on 2025-09-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generator', '0003_update_gemini_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneration',
            name='ai_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=50, verbose_name='AI Model'),
        ),
    ]
