# Generated by Django 4.2.24 on 2025-09-23 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploads.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file', models.FileField(upload_to=uploads.models.upload_file_path, verbose_name='File')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('pptx', 'PowerPoint Presentation'), ('txt', 'Text File'), ('image', 'Image File'), ('video', 'Video File'), ('audio', 'Audio File'), ('other', 'Other')], max_length=20, verbose_name='File Type')),
                ('file_size', models.BigIntegerField(verbose_name='File Size (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='uploading', max_length=20, verbose_name='Status')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from the file using OCR or other methods', null=True, verbose_name='Extracted Text')),
                ('detected_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Detected Language')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata extracted from the file', verbose_name='File Metadata')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is Processed')),
                ('processing_error', models.TextField(blank=True, null=True, verbose_name='Processing Error')),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum of the file', max_length=64, null=True, verbose_name='File Checksum')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='courses.course')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], max_length=10, verbose_name='Log Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='uploads.uploadedfile')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Shared with Email')),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('download', 'View & Download'), ('edit', 'View, Download & Edit')], default='view', max_length=20, verbose_name='Permission')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Access Count')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='uploads.uploadedfile')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Share',
                'verbose_name_plural': 'File Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Version Number')),
                ('file', models.FileField(upload_to=uploads.models.upload_file_path, verbose_name='File')),
                ('file_size', models.BigIntegerField(verbose_name='File Size (bytes)')),
                ('change_notes', models.TextField(blank=True, null=True, verbose_name='Change Notes')),
                ('checksum', models.CharField(blank=True, max_length=64, null=True, verbose_name='File Checksum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_versions', to=settings.AUTH_USER_MODEL)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='uploads.uploadedfile')),
            ],
            options={
                'verbose_name': 'File Version',
                'verbose_name_plural': 'File Versions',
                'ordering': ['-version_number'],
                'unique_together': {('original_file', 'version_number')},
            },
        ),
    ]
